
import { StyleSheet } from 'react-native';
import { COLORS } from './constants';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4fcff',
    paddingTop: 36,
    paddingHorizontal: 10,
    borderRadius: 18,
  },
  headerContainer: {
        width: '120%',
        backgroundColor: COLORS.background,
        alignItems: 'center',
        justifyContent: 'center',
    marginTop:-50,
    marginLeft: -20,
        paddingTop: 52,
        paddingBottom: 10,
        borderBottomWidth: 0.5,
        borderBottomColor: '#e0e7ef',
        paddingVertical: 10,
        zIndex: 10,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
        marginBottom: 20,
      },
      logoText: {
        fontFamily: 'Poppins_700Bold',
        fontSize: 24,
        letterSpacing: 0.5,
      },
  header: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
    marginBottom: 8,
    color: '#222',
    marginLeft: 6,
  },
  banner: {
    width: '100%',
    height: 80,
    borderRadius: 14,
    marginBottom: 12,
  },
  scrollArea: {
    flex: 1,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  iconBox: {
    borderRadius: 8,
    padding: 6,
    marginRight: 8,
  },
  iconText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 18,
  },
  cardTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#222',
  },
  cardSubTitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#7e7e7e',
    marginBottom: 2,
    marginLeft: 2,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    marginLeft: 2,
  },
  infoText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#6a6a6a',
  },
  dot: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: '#b0b0b0',
    marginHorizontal: 6,
  },
  cardDesc: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#444',
    marginBottom: 10,
    marginLeft: 2,
  },
  participantsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 2,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: -8,
    borderWidth: 2,
    borderColor: '#fff',
  },
  participantsText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#666',
    marginLeft: 16,
    marginRight: 8,
  },
  joinBtn: {
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 18,
    marginLeft: 'auto',
  },
  joinBtnText: {
    fontFamily: 'Poppins_400Regular',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.22)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '86%',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 22,
    alignItems: 'center',
    elevation: 6,
  },
  modalTitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#222',
  },
  input: {
    fontFamily: 'Poppins_400Regular',
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    fontSize: 15,
    backgroundColor: '#f7f7f7',
  },
  modalBtn: {
    backgroundColor: '#4ea5ff',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 30,
    marginTop: 4,
    marginBottom: 12,
    width: '100%',
    alignItems: 'center',
  },
  modalBtnText: {
    fontFamily: 'Poppins_400Regular',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  cancelText: {
    fontFamily: 'Poppins_400Regular',
    color: '#a084fa',
    marginTop: 4,
    fontSize: 14,
  },
});

export default styles;
