import { StyleSheet } from 'react-native';
import  { COLORS } from './constants';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7FDFF',
    paddingHorizontal: 20,
    paddingTop: 32,
  },
   headerContainer: {
      width: '120%',
      backgroundColor: COLORS.background,
      alignItems: 'center',
      justifyContent: 'center',
  marginTop:-50,
  marginLeft: -20,
      paddingTop: 62,
      paddingBottom: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: '#e0e7ef',
      paddingVertical: 10,
      zIndex: 10,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.07,
      shadowRadius: 6,
      marginBottom: 20,
    },
    logoText: {
      fontFamily: 'Poppins_700Bold',
      fontSize: 24,
      letterSpacing: 0.5,
    },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  header: {
    fontSize: 24,
    fontFamily: 'Poppins_700Bold',
    color: '#22223B',
  },
  addButton: {
    backgroundColor: '#22C55E',
    borderRadius: 20,
    padding: 7,
  },
  calendarContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 22,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  calendarHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  calendarHeader: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#22223B',
  },
  calendarNav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  calendarDaysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
    marginTop: 2,
  },
  calendarDayName: {
    width: 28,
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
    fontSize: 13,
    color: '#A1A1AA',
  },
  calendarWeek: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  calendarDay: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDayText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    color: '#22223B',
  },
  calendarDaySelected: {
    backgroundColor: '#22C55E',
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontFamily: 'Poppins_700Bold',
  },
  calendarDayEvent: {
    backgroundColor: '#E0F2FE',
  },
  calendarDayTextEvent: {
    color: '#2563EB',
    fontFamily: 'Poppins_700Bold',
  },
  upcomingHeader: {
    fontSize: 17,
    fontFamily: 'Poppins_700Bold',
    marginVertical: 10,
    color: '#22223B',
  },
  eventsList: {
    marginBottom: 16,
  },
  eventCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  eventIcon: {
    marginRight: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 8,
  },
  eventInfo: {
    flex: 1,
  },
  eventTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    color: '#22223B',
  },
  eventInstructor: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#6B7280',
    marginVertical: 2,
  },
  eventTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  eventTime: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 32,
  },
  seeRequestsBtn: {
    backgroundColor: '#22C55E',
    borderRadius: 8,
    paddingVertical: 15,
    paddingHorizontal: 18,
    flex: 1,
    marginRight: 8,
    alignItems: 'center',
  },
  addPartnerBtn: {
    backgroundColor: '#2563EB',
    borderRadius: 8,
    paddingVertical: 15,
    paddingHorizontal: 18,
    flex: 1,
    marginLeft: 8,
    alignItems: 'center',
  },
  seeRequestsText: {
    color: '#fff',
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
  },
  addPartnerText: {
    color: '#fff',
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    textAlign: 'center',
  },
});
